.TH moving_bar "1" "April 2012" "moving_bar" "User Commands"
.SH NAME
moving_bar \- moving bar stimulus for psycho- or neuro-physiological experiments
.SH SYNOPSIS
.B moving_bar
[\fIOPTION\fR]...
.SH DESCRIPTION
This application generates a moving bar at a giving frequency so that
it can be used with programs which average over time.
.TP
\-window
uses a window to display the stimulus (default is full screen)
.TP
\-w WIDTH
sets the width of the stimulus
.TP
\-h HEIGHT sets the height of the stimulus
sets the notch filter frequency
.TP
\-angle DEGREES
sets the angle of the stimulus
.TP
\-length LENGTH
sets the length of the bar
.TP
\-freq FREQUENCY
sets the frequency of the stimulus
.SH AUTHOR
moving_bar was written by Matthias Henning, Bernd Porr and Graeme Hattan.

